_target_: 'diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner'
checkpoints: 
    train0: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/bet/train0/checkpoints/epoch=0050-test_mean_score=0.944.ckpt'
    train1: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/bet/train1/checkpoints/epoch=0050-test_mean_score=0.860.ckpt'
    train2: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/bet/train2/checkpoints/epoch=0200-test_mean_score=0.833.ckpt'

checkpoint: ${checkpoints.train1}
task: 'lift_ph'
dataset_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/robomimic/datasets/lift/ph/image.hdf5'
algo: 'bet'
device: 'cuda:0'
attack: True
attack_type: 'patch'
seed: 1023
patch_type: 'universal_transparent'
# epsilons: [0.01, 0.03, 0.1, 0.3, 0.5]
# epsilons: [0.015625, 0.03125, 0.0625, 0.125, 0.2, 0.3, 0.5, 1.0]
epsilon: 0.0625
clip_min: 0
clip_max: 1
view: 'robot0_eye_in_hand_image'
perturbations: [0.15, 0.15, 0., 0., 0., 0., 0.]
num_iter: 40
batch_size: 8
targeted: True
rand_int: True
eps_iter: 0.02
norm: 'linf'
rand_target: False
action_space: None
n_train: 2
n_test: 50
n_envs: 26
n_inits: 7
log: False
max_steps: 400
patch_size: 16
x_loc: 0
y_loc: 0
n_epochs: 100

data_file: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/lstm_gmm/train_0/data.pkl'
# patch_file: None
# patch_file: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/lstm_gmm/correct_patches/patch_${x_loc}_${y_loc}_${patch_size}.pkl'
# patch_file: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/plots/universal_patch/universal_patch_transparent_y_60_200iters_eps_0.0625.npy'
patch_file: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/bet/train0/checkpoints/untar_pert_0.0625_epoch_2_mean_score_0.1_robot0_eye_in_hand_image.pkl'
patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/bet/train0/checkpoints/untar_pert_0.0625_epoch_2_mean_score_0.1_robot0_eye_in_hand_image.pkl'


# pgd:
#  eta_bound:
#  num_iter:
#  norm:
#  rand_int:
