_target_: 'diffusion_policy.env_runner.robomimic_image_runner.AdversarialRobomimicImageRunnerIBC'
# checkpoints: ['/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/ibc_dfo/train_0/checkpoints/epoch=1900-test_mean_score=0.955.ckpt',
# '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/ibc_dfo/train_1/checkpoints/epoch=3050-test_mean_score=0.773.ckpt',
# '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/ibc_dfo/train_2/checkpoints/epoch=2100-test_mean_score=1.000.ckpt'
# ]
checkpoints: ['/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/ibc_dfo/train_1/checkpoints/epoch=3050-test_mean_score=0.773.ckpt']
task: 'lift_ph'
dataset_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/robomimic/datasets/lift/ph/image.hdf5'
algo: 'ibc'
n_envs: 28
log: True
device: 'cuda:0'
attack: True
attack_type: 'pgd'
# epsilons: [0.01, 0.03, 0.1, 0.3, 0.5]
epsilons: [0.015625, 0.03125, 0.0625, 0.125]
# epsilons: [0.125]
clip_min: 0
clip_max: 1
view: 'both'
num_iter: 100
rand_int: True
eps_iter: [0.01]
norm: 'linf'
rand_target: False
action_space: None
n_train: 6
n_test: 50
target_perturbations: True
perturbations: [0, 0.15, 0.15, 0, 0, 0, 0]


# pgd:
#  eta_bound:
#  num_iter:
#  norm:
#  rand_int:
