_target_: 'diffusion_policy.env_runner.robomimic_image_runner.AdversarialRobomimicImageRunnerIBC'
checkpoint: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/ibc_dfo/train_2/checkpoints/epoch=2100-test_mean_score=1.000.ckpt'
task: 'lift_ph'
dataset_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/robomimic/datasets/lift/ph/image.hdf5'
algo: 'ibc'
n_envs: 1
log: False
device: 'cpu'
attack: True
attack_type: 'pgd'
# epsilons: [0.01, 0.03, 0.1, 0.3, 0.5]
epsilons: [0.2]
clip_min: 0
clip_max: 1
view: 'both'
num_iter: 40
rand_int: True
eta_bound: [0.15, 0.1, 0.05]
norm: 'linf'
rand_target: True
action_space: None


# pgd:
#  eta_bound:
#  num_iter:
#  norm:
#  rand_int:
