_target_: 'diffusion_policy.env_runner.robomimic_image_runner.AdversarialRobomimicImageRunner'
checkpoint: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/lstm_gmm/train_0/checkpoints/epoch=1100-test_mean_score=1.000.ckpt'
task: 'lift_ph'
dataset_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/robomimic/datasets/lift/ph/image.hdf5'
algo: 'lstm_gmm'
n_envs: 4
log: True
device: 'cpu'
attack: True
epsilons: [0.01, 0.03, 0.1, 0.3, 0.5]