_target_: 'diffusion_policy.env_runner.robomimic_image_runner.AdversarialRobomimicImageRunnerLSTM'
checkpoints: 
    train0: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/lstm_gmm/train_0/checkpoints/epoch=1100-test_mean_score=1.000.ckpt'
    train1: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/lstm_gmm/train_1/checkpoints/epoch=0300-test_mean_score=1.000.ckpt'
    train2: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/lstm_gmm/train_2/checkpoints/epoch=0300-test_mean_score=1.000.ckpt'

checkpoint: ${checkpoints.train0}

task: 'lift_ph'
dataset_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/robomimic/datasets/lift/ph/image.hdf5'
algo: 'lstm_gmm'
n_envs: 26
n_test: 50
n_train: 2
log: True
device: 'cuda:0'
attack: True
attack_type: 'fgsm'
targeted: True
# epsilons: [0.01, 0.03, 0.1, 0.3, 0.5]
# epsilons: [0.01953125, 0.03125, 0.0625, 0.125]
# epsilons: [0.125, 0.0625, 0.03125, 0.015625]
epsilon: 0.0625
eps_iter: 0.01
perturbations: [0.25, 0.25, 0., 0., 0., 0., 0]
clip_min: 0
clip_max: 1
view: 'both'
rand_int: False
action_space: None
rand_target: False
n_iter: 40
norm: 'linf'
max_steps: 400
patch_size: 16
seed: 1023
# pgd:
#  eta_bound:
#  num_iter:
#  norm:
#  rand_int:

