_target_: 'diffusion_policy.env_runner.robomimic_adv_patch_trainer.AdvPatchRobomimicImageRunner'
checkpoints: 
    train0: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/ibc_dfo/train_0/checkpoints/epoch=1900-test_mean_score=0.955.ckpt'
    train1: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/ibc_dfo/train_1/checkpoints/epoch=3050-test_mean_score=0.773.ckpt'
    train2: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/ibc_dfo/train_2/checkpoints/epoch=2100-test_mean_score=1.000.ckpt'

checkpoint: ${checkpoints.train0}
task: 'lift_ph'
dataset_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/robomimic/datasets/lift/ph/image.hdf5'
algo: 'ibc_dfo'
device: 'cpu'
attack: True
attack_type: 'patch'
seed: 1023
patch_type: 'universal_transparent'
# epsilons: [0.01, 0.03, 0.1, 0.3, 0.5]
# epsilons: [0.015625, 0.03125, 0.0625, 0.125, 0.2, 0.3, 0.5, 1.0]
epsilon: 0.125
clip_min: 0
clip_max: 1
view: 'robot0_eye_in_hand_image'
perturbations: [0.15, 0.15, 0., 0., 0., 0., 0.]
num_iter: 40
batch_size: 8
targeted: True
rand_int: True
eps_iter: 0.02
norm: 'linf'
rand_target: False
action_space: None
n_train: 2
n_test: 2
n_envs: 2
n_inits: 7
log: False
max_steps: 400
patch_size: 16
x_loc: 0
y_loc: 0
n_epochs: 100

data_file: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/lstm_gmm/train_0/data.pkl'
# patch_file: None
# patch_file: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/lstm_gmm/correct_patches/patch_${x_loc}_${y_loc}_${patch_size}.pkl'
patch_file: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/plots/universal_patch/ibc_samesamiter100_universal_patch_transparent_y_15_1iters_2000sap_eps_0.125.npy'


# pgd:
#  eta_bound:
#  num_iter:
#  norm:
#  rand_int:
