_target_: 'diffusion_policy.env_runner.robomimic_image_runner.AdversarialRobomimicImageRunnerBET'
checkpoints: 
    train1: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/pre_trained_checkpoints/square/vq_bet/train_1/checkpoints/epoch=0150-test_mean_score=0.560.ckpt'

checkpoint: ${checkpoints.train1}
task: 'square_ph'
dataset_path: '/teamspace/studios/this_studio/bc_attacks/robomimic/datasets/square/ph/image.hdf5'
algo: 'VQ-BET'
n_envs: 26
n_test: 50
n_train: 2
log: True
device: 'cuda:3'
attack: True
attack_type: 'pgd'
targeted: True
clip_min: 0
clip_max: 1
view: 'both'
n_iter: 40

patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/pre_trained_checkpoints/square/vq_bet/train_1/checkpoints/epoch=0150-test_mean_score=0.560.ckpt'


epsilons:
    epsilon0: 0.03125
    epsilon1: 0.0625
    epsilon2: 0.125
epsilon: ${epsilons.epsilon1}
eps_iter: 0.01



rand_target: False
action_space: None
rand_int: False
perturbations: [0.15, 0.15, 0, 0, 0, 0, 0]
num_iter: 40
norm: 'linf'
max_steps: 400

save_video: False
n_vis: 3