# _target_: 'diffusion_policy.env_runner.robomimic_image_runner.AdversarialRobomimicImageRunnerDP'
_target_: 'diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner'
checkpoints:
    #dp checkpoint
    train0: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/pre_trained_checkpoints/square/diffusion_policy_cnn/train_0/checkpoints/epoch=1250-test_mean_score=1.000.ckpt'
    # train0: '/home/ak/Documents/Adversarial_diffusion_policy/pre_trained_checkpoints/square/diffusion_policy_cnn/train_0/checkpoints/epoch=1250-test_mean_score=1.000.ckpt'
#    ibc
#     train0: '/home/ak/Documents/Adversarial_diffusion_policy/pre_trained_checkpoints/square/ibc_dfo/train_0/checkpoints/epoch=2950-test_mean_score=0.045.ckpt'
#     lstm
#     train0: '/home/ak/Documents/Adversarial_diffusion_policy/pre_trained_checkpoints/square/lstm_gmm/train_0/checkpoints/epoch=1400-test_mean_score=0.864.ckpt'
     #vanilla bc
#     train0 : '/home/ak/Documents/Adversarial_diffusion_policy/data/outputs/ALLFixed-Final-Run1-BC-Square-PH-Seed0_2024.09.28/10.44.38_train_robomimic_image_square/checkpoints/epoch=0350-test_mean_score=0.260.ckpt'
     #vq-bet
#     train0 : '/home/ak/Documents/Adversarial_diffusion_policy/data/outputs/Latest-Final-VQ-BET-Square-PH-Run1-Seed0_2024.09.26/16.06.15_train_vq_bet_image_square_image/checkpoints/epoch=0250-test_mean_score=0.560.ckpt'


checkpoint: ${checkpoints.train0}
task: 'square_image'
dataset_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/robomimic/datasets/square/ph/image.hdf5'
algo: 'Diffusion_Policy'
#algo: 'ibc_dfo'
#algo: 'lstm_gmm'
#algo: 'bc'
#algo: 'VQ-BET'
n_envs: 20
n_test: 50
n_train: 2
log: True
device: 'cuda:0'
attack: False

attack_type: 'patch'
patch_paths:
    diffusion_policy: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/task_transfer_patch/diffusion_policy_both.pkl'
    vanilla_bc: '/home/ak/Documents/Adversarial_diffusion_policy/diffusion_policy/task_transfer_patchs/bc_untar_pert_0.0625_epoch_20_mean_score_0.0_both.pkl'
    lstm_gmm: '/home/ak/Documents/Adversarial_diffusion_policy/diffusion_policy/task_transfer_patchs/lstm_gmm_both.pkl'

    ibc: '/home/ak/Documents/Adversarial_diffusion_policy/diffusion_policy/task_transfer_patchs/lstm_gmm_both.pkl'

    vqbet: '/home/ak/Documents/Adversarial_diffusion_policy/diffusion_policy/task_transfer_patchs/vqbet_both.pkl'
patch_path: ${patch_paths.diffusion_policy}
#patch_path: ${patch_paths.vanilla_bc}
#patch_path: ${patch_paths.ibc}
#patch_path: ${patch_paths.rand}
#patch_path: ${patch_paths.vqbet}
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/vanilla_bc/train_0/checkpoints/untar_pert_0.0625_epoch_15_mean_score_0.62_robot0_eye_in_hand_image.pkl'
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/lstm_gmm/train_0/checkpoints/untar_pert_0.0625_epoch_5_mean_score_0.0_robot0_eye_in_hand_image.pkl'
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/ibc_dfo/train_0/checkpoints/untar_pert_0.0625_epoch_10_mean_score_0.82_robot0_eye_in_hand_image.pkl'
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/bet/train6/checkpoints/untar_pert_0.0625_epoch_25_mean_score_0.0_robot0_eye_in_hand_image_just_nobs_reg.pkl'
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/random_patch.pkl'


targeted: False
# epsilons: [0.015625, 0.03125, 0.0625, 0.125]
# epsilons: [0.01, 0.03, 0.1, 0.3, 0.5]
# epsilons: [0.0078125, 0.01953125, 0.03125, 0.0625, 0.125]
epsilons:
    zero: 0.00
    first: 0.015625
    second: 0.03125
    third: 0.0625
    fourth: 0.125
    fifth: 0.25

epsilon: ${epsilons.fourth}
clip_min: 0
clip_max: 1
# view: 'robot0_eye_in_hand_image'
view: 'both'
rand_target: False
action_space: None
rand_int: False
# perturbations: [100, 100]
perturbations: [0.45, 0.45, 0, 0, 0, 0, 0, 0, 0, 0]
eps_iter: 0.01
num_iter: 4
norm: 'linf'
attack_after_timesteps: 0.9
max_steps: 400
save_video: False
n_vis: 3
# pgd:
#  eta_bound:
#  num_iter:
#  norm:
#  rand_int: